### ISSUE TITLE
Multi Channel Support

### ISSUE THREAD

**Issue by XerockXMG** [roundaboutluke/porygon#8]
For people who have multiple Discord servers. Instead of running 1 Porygon for each server.

Could potentially be done by allowing for an array of channelIDs and looping through them after generating the payload

**Comment by roundaboutluke** [comment]
I'll get this in tonight 👍

**Comment by roundaboutluke** [comment]
added in https://github.com/roundaboutluke/porygon/commit/428312e0affe0b1ae745df8433942eb1531d2116
