### ISSUE TITLE
Error handling for 1st start

### ISSUE THREAD

**Issue by roundaboutluke** [roundaboutluke/porygon#9]
On first run Porygon throws a nasty error from the Discord API - Purely cosmetic as will then save the new message ID but needs fixing to display a first run message or something instead to avoid confusion with some error handling

9|porygon  | error editing message, HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"message_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"thiswillgetreplacedautomagicallywiththeidofthemessagethebotposts\" is not snowflake."}]}}}

**Comment by roundaboutluke** [comment]
Shouldn't happen with latest config.example

https://github.com/roundaboutluke/porygon/commit/428312e0affe0b1ae745df8433942eb1531d2116

**Comment by roundaboutluke** [comment]
reopening this as config.example is confusing without a fake message id there so the error will still happen on first run until I move to toml for the config and move the messageid storing somewhere else

**Comment by Dewpg** [comment]
I just pulled today, and it still happens.

**Comment by roundaboutluke** [comment]
Fixed in develop, will merge when further changes are in due to major config changes
